"""initial_schema_all_tables

Revision ID: 26a56b2d123f
Revises: 
Create Date: 2026-05-13 16:51:12.614804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26a56b2d123f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyst_estimates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('ntm_eps_consensus', sa.Float(), nullable=True),
    sa.Column('ntm_eps_consensus_3m_ago', sa.Float(), nullable=True),
    sa.Column('ntm_revenue_consensus', sa.Float(), nullable=True),
    sa.Column('ntm_ebitda_consensus', sa.Float(), nullable=True),
    sa.Column('ev_ntm_ebitda', sa.Float(), nullable=True),
    sa.Column('pe_ntm', sa.Float(), nullable=True),
    sa.Column('analyst_count', sa.Integer(), nullable=True),
    sa.Column('buy_count', sa.Integer(), nullable=True),
    sa.Column('hold_count', sa.Integer(), nullable=True),
    sa.Column('sell_count', sa.Integer(), nullable=True),
    sa.Column('mean_rating', sa.Float(), nullable=True),
    sa.Column('price_target_median', sa.Float(), nullable=True),
    sa.Column('short_interest_pct_float', sa.Float(), nullable=True),
    sa.Column('shares_float', sa.Float(), nullable=True),
    sa.Column('short_shares', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'as_of_date', name='uq_estimates_ticker_date')
    )
    op.create_index('ix_estimates_ticker_date', 'analyst_estimates', ['ticker', 'as_of_date'], unique=False)
    op.create_table('text_embeddings',
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('computed_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('vector_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('ticker', 'model_name'),
    sa.UniqueConstraint('ticker', 'model_name', name='uq_embedding_ticker_model')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('watchlists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('query_ticker', sa.String(length=10), nullable=False),
    sa.Column('watchlist_size', sa.Integer(), nullable=False),
    sa.Column('sector_lock', sa.String(length=4), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlists_user_id'), 'watchlists', ['user_id'], unique=False)
    op.create_table('alert_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('watchlist_id', sa.String(length=36), nullable=False),
    sa.Column('peer_ticker', sa.String(length=10), nullable=False),
    sa.Column('alert_date', sa.Date(), nullable=False),
    sa.Column('prev_rps', sa.Float(), nullable=True),
    sa.Column('curr_rps', sa.Float(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('webhook_url', sa.String(length=512), nullable=True),
    sa.Column('delivered', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_logs_watchlist_id'), 'alert_logs', ['watchlist_id'], unique=False)
    op.create_table('score_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('watchlist_id', sa.String(length=36), nullable=False),
    sa.Column('peer_ticker', sa.String(length=10), nullable=False),
    sa.Column('score_date', sa.Date(), nullable=False),
    sa.Column('rps', sa.Float(), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('conviction_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_history_watchlist_id'), 'score_history', ['watchlist_id'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('watchlist_id', sa.String(length=36), nullable=False),
    sa.Column('peer_ticker', sa.String(length=10), nullable=False),
    sa.Column('peer_name', sa.String(length=256), nullable=True),
    sa.Column('rps', sa.Float(), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('conviction_score', sa.Float(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_items_watchlist_id'), 'watchlist_items', ['watchlist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_items_watchlist_id'), table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index(op.f('ix_score_history_watchlist_id'), table_name='score_history')
    op.drop_table('score_history')
    op.drop_index(op.f('ix_alert_logs_watchlist_id'), table_name='alert_logs')
    op.drop_table('alert_logs')
    op.drop_index(op.f('ix_watchlists_user_id'), table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('text_embeddings')
    op.drop_index('ix_estimates_ticker_date', table_name='analyst_estimates')
    op.drop_table('analyst_estimates')
    # ### end Alembic commands ###
